export const ACTIONS = {
    INIT: "ACTIONS$INIT",
    WEB_SOCKET_ONOPEN: "ACTIONS$WEB_SOCKET_ONOPEN",
    DATA_RECEIVED: "ACTIONS$DATA_RECEIVED",
    QUERY: "ACTIONS$QUERY",
}
export const ACTION_STATUS = {
    SUCCESS: "ACTION_STATUS$SUCCESS",
    FAILURE: "ACTION_STATUS$FAILURE",
}
